### ISSUE TITLE
Music doesn't loop properly

### ISSUE THREAD

**Issue by dani-dandelion** [aldelaro5/BugFables-AssetsRedirector#1]
I'm attempting to make a music mod. I can get the replaced tracks to play, but they seem to loop where the original tracks would instead, cutting off awkwardly in the middle. Trying to match the original song length doesn't help, because most songs don't restart from the beginning in the original files. I tried setting my own "LOOPSTART" and "LOOPEND" parameters in the replacement .ogg files, but they aren't respected at all.

**Comment by aldelaro5** [comment]
So the way looping works in bug fables is there's a text file that goes per line (they are ordered by song indexes), it has the end point followed by the start point in seconds (999 if it loops the whole file). NORMALLY, this mod should allow you to edit both so that the game can have the loop points changed.

However, you and another person ik didn't seem to get this to work which is strange.

I am currently on hiatus with bug fables (maybe will come back somewhere in 2022, but I can't promise ANYTHING on WHEN, just that I will come back eventually) so I'll leave this issue open until then.

**Comment by dani-dandelion** [comment]
I think I have the text files you mentioned, exported via UABE. For example, `Title-resources.assets-6757-AudioClip.txt`, which I believe corresponds to the title music `Title.wav` (or .ogg). The text file contains this:

```
0 AudioClip Base
 1 string m_Name = "Title"
 0 int m_LoadType = 2
 0 int m_Channels = 2
 0 int m_Frequency = 44100
 0 int m_BitsPerSample = 16
 0 float m_Length = 57.808979
 0 bool m_IsTrackerFormat = false
 1 bool m_Ambisonic = false
 0 int m_SubsoundIndex = 0
 0 bool m_PreloadAudioData = true
 0 bool m_LoadInBackground = false
 1 bool m_Legacy3D = true
 0 StreamedResource m_Resource
  1 string m_Source = "resources.resource"
  0 UInt64 m_Offset = 49087232
  0 UInt64 m_Size = 829856
 1 int m_CompressionFormat = 1
```

I put this text file in the same folder as the Asset Redirector music files, renamed it several times, and even changed `m_Name` to point to a different music file, but it doesn't seem to do anything. Changing `m_Length` to the new song's length doesn't do anything, either.

**Comment by aldelaro5** [comment]
ok, no this isn't how it works.

First off, there's a reason I instruct in the readme to use utinyripper instead of UABE: uabe just messes up in ways that it really shouldn't for the export and it's kind of broken. For example, this file is just the audioclip ressources file in text format, but changing it won't change anything in game because the ressources already exists serialised in binary form in the game. You would likely need to edit it with code using a bepinex plugin.

How it ACTUALLY works is there is a TextAsset in the data folder `/Assets/Resources/data` called `LoopPoints` which is the file you want to edit. Again, don't use UABE for this (you should only use UABE to change SOME sprites out of an atlas because uTinyRipper doesn't allow you to rip the sprites individually).

Honestly, I probably should fork utinyripper at one point because this export nonsense is confusing everyone and I hate it :(

but yeah you only care about this TextAsset. It exports as .bytes, but it's a txt. The mod supports .bytes, .txt or no extension.

**Comment by dani-dandelion** [comment]
I found the LoopPoints file, and edited it. I couldn't tell which line corresponded to which music file, so I just changed them all to 999;999 for now (except the ones that are 0;0 by default, I left those alone). The new songs play to their full length and loop seamlessly. Thank you so much for all your help! :D
