### ISSUE TITLE
Can't seem to resize sprites

### ISSUE THREAD

**Issue by SparkCadson** [aldelaro5/BugFables-AssetsRedirector#2]
When I try to edit a sprite and fit it within the boundries, it's too small and I can't figure out a way to change the size.

**Comment by aldelaro5** [comment]
Hey, so I really should make this clear in the readme, but this project is very much deprecated, It means I won't support it for the forseeable future because it's honestly not great at all.

There are much better ways to do what this was trying to do. This was a prototype made to experiment with stuff and while people found it useful, it was never made for actual projects in the first place.

I have plans to setup better modding infrastructure involving unity more instead of this, but because I am busy right now on documenting the internals of the game (precisely to know more for modding such as tools like these work better), no alternative exists yet.

I will try to point you to the right direction, but as far as this repo is concerned, I can't do much because this feature is not supported so I'll close this as "wontfix".

What you want to look into is to use unity itself (specifically version 2018.4.12f1) to build what are called asset bundles. They are serialised archives of unity's assets which a bepinex plugin can load programmatically. This allows you to do everything you need with assets including resizing once you use the original ressources redirector plugin (not this repo, it's not supported).

Hopefully what I said points you to the right direction, but I really can't help for this.
